# Generated by Django 5.0.9 on 2024-10-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_tickettype'),
        ('movie', '0006_movie_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='discount',
        ),
        migrations.CreateModel(
            name='MovieTicketTypeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tickettype')),
            ],
            options={
                'unique_together': {('movie', 'ticket_type')},
            },
        ),
    ]
