# Generated by Django 5.0.9 on 2024-10-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_ticket_seat_number_ticket_screening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tickets',
        ),
    ]
