# Generated by Django 5.0.9 on 2024-11-01 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.booking'),
            preserve_default=False,
        ),
    ]
