# Generated by Django 5.0.9 on 2024-11-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_ticket_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
