# Generated by Django 5.0.9 on 2024-11-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_ticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(default=0),
        ),
    ]
