# Generated by Django 5.0.9 on 2024-11-08 04:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_ticket_seat_ticket_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='promotion',
            name='valid_to',
            field=models.DateField(default=datetime.date(2024, 12, 8)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
