# Generated by Django 5.0.9 on 2024-12-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_promotion_description_alter_promotion_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='showroom',
            field=models.IntegerField(default=0),
        ),
    ]
