# Generated by Django 5.0.9 on 2024-12-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_booking_showroom'),
        ('movie', '0015_seatlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='showroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movie.showroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.showroom'),
        ),
    ]
