# Generated by Django 5.0.9 on 2024-10-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
