# Generated by Django 5.0.9 on 2024-10-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
    ]
