# Generated by Django 5.0.9 on 2024-10-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='billing_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(default='', max_length=15),
        ),
    ]
