# Generated by Django 5.0.9 on 2024-10-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_billing_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
