# Generated by Django 5.0.9 on 2024-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='masked_card',
        ),
        migrations.AddField(
            model_name='transaction',
            name='encrypted_card_number',
            field=models.CharField(default=9999999999999999, max_length=255),
            preserve_default=False,
        ),
    ]
