movies = [
    (
        title="Avatar: The Way of Water",
        category="Action/Adventure/Sci-Fi",
        cast=["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Stephen Lang"],
        director="James Cameron",
        producer="James Cameron",
        synopsis="Jake Sully and Ney'tiri, now parents, must leave their home and explore the regions of Pandora to face a renewed threat from the RDA.",
        trailer_url="https://www.youtube.com/watch?v=d9MyW72ELq0",
        rating="PG-13",
        release_date="2022-12-16",
        movie_duration=192
    ),
    (
        title="Spider-Man: Across the Spider-Verse",
        category="Animation/Action/Adventure",
        cast=["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Jake Johnson"],
        director="Joaquim Dos Santos",
        producer="Amy Pascal",
        synopsis="Miles Morales returns for the next chapter of the Spider-Verse saga, facing off against a powerful new villain across multiple dimensions.",
        trailer_url="https://www.youtube.com/watch?v=cqGjhVJWtEg",
        rating="PG",
        release_date="2023-06-02",
        movie_duration=140
    ),
    (
        title="Oppenheimer",
        category="Drama/History",
        cast=["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
        director="Christopher Nolan",
        producer="Emma Thomas",
        synopsis="The story of J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
        trailer_url="https://www.youtube.com/watch?v=bK6ldnjE3Y0",
        rating="R",
        release_date="2023-07-21",
        movie_duration=180
    ),
    (
        title="The Super Mario Bros. Movie",
        category="Animation/Adventure/Comedy",
        cast=["Chris Pratt", "Anya Taylor-Joy", "Charlie Day", "Jack Black"],
        director="Aaron Horvath",
        producer="Chris Meledandri",
        synopsis="The iconic plumber Mario travels through the Mushroom Kingdom with Princess Peach to save his brother, Luigi, from Bowser.",
        trailer_url="https://www.youtube.com/watch?v=TnGl01FkMMo",
        rating="PG",
        release_date="2023-04-05",
        movie_duration=92
    ),
    (
        title="Dune: Part Two",
        category="Adventure/Drama/Sci-Fi",
        cast=["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Josh Brolin"],
        director="Denis Villeneuve",
        producer="Denis Villeneuve",
        synopsis="Paul Atreides unites with Chani and the Fremen to seek revenge against those who destroyed his family, while confronting a prophecy of a great war.",
        trailer_url="https://www.youtube.com/watch?v=Way9Dexny3w",
        rating="PG-13",
        release_date="2024-03-15",
        movie_duration=165
    ),
    (
        title="Barbie",
        category="Comedy/Fantasy",
        cast=["Margot Robbie", "Ryan Gosling", "Simu Liu", "America Ferrera"],
        director="Greta Gerwig",
        producer="Margot Robbie",
        synopsis="Barbie suffers a crisis that leads her to question her world and her existence.",
        trailer_url="https://www.youtube.com/watch?v=pBk4NYhWNMM",
        rating="PG-13",
        release_date="2023-07-21",
        movie_duration=114
    ),
    (
        title="Guardians of the Galaxy Vol. 3",
        category="Action/Adventure/Comedy",
        cast=["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Bradley Cooper"],
        director="James Gunn",
        producer="Kevin Feige",
        synopsis="The Guardians must band together to protect one of their own as they uncover secrets of Rocket's past.",
        trailer_url="https://www.youtube.com/watch?v=u3V5KDHRQvk",
        rating="PG-13",
        release_date="2023-05-05",
        movie_duration=149
    ),
    (
        title="John Wick: Chapter 4",
        category="Action/Thriller",
        cast=["Keanu Reeves", "Laurence Fishburne", "Ian McShane", "Donnie Yen"],
        director="Chad Stahelski",
        producer="Basil Iwanyk",
        synopsis="John Wick faces his deadliest adversaries yet as he seeks out a path to defeating the High Table.",
        trailer_url="https://www.youtube.com/watch?v=qEVUtrk8_B4",
        rating="R",
        release_date="2023-03-24",
        movie_duration=169
    ),
    (
        title="Black Panther: Wakanda Forever",
        category="Action/Adventure/Drama",
        cast=["Letitia Wright", "Lupita Nyong'o", "Danai Gurira", "Winston Duke"],
        director="Ryan Coogler",
        producer="Kevin Feige",
        synopsis="The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
        trailer_url="https://www.youtube.com/watch?v=_Z3QKkl1WyM",
        rating="PG-13",
        release_date="2022-11-11",
        movie_duration=161
    ),
    (
        title="The Marvels",
        category="Action/Adventure/Sci-Fi",
        cast=["Brie Larson", "Teyonah Parris", "Iman Vellani", "Samuel L. Jackson"],
        director="Nia DaCosta",
        producer="Kevin Feige",
        synopsis="Carol Danvers, Kamala Khan, and Monica Rambeau join forces to save the universe.",
        trailer_url="https://www.youtube.com/watch?v=wjfZZB0Qp6k",
        rating="PG-13",
        release_date="2023-11-10",
        movie_duration=105
    ),
    (
        title="Mission: Impossible – Dead Reckoning Part One",
        category="Action/Adventure/Thriller",
        cast=["Tom Cruise", "Hayley Atwell", "Ving Rhames", "Simon Pegg"],
        director="Christopher McQuarrie",
        producer="Tom Cruise",
        synopsis="Ethan Hunt and his IMF team must track down a terrifying new weapon that threatens all of humanity.",
        trailer_url="https://www.youtube.com/watch?v=avz06PDqDbM",
        rating="PG-13",
        release_date="2023-07-12",
        movie_duration=163
    ),
    (
        title="Fast X",
        category="Action/Crime/Thriller",
        cast=["Vin Diesel", "Michelle Rodriguez", "Jordana Brewster", "Jason Momoa"],
        director="Louis Leterrier",
        producer="Vin Diesel",
        synopsis="Dom Toretto and his family confront the most lethal opponent they've ever faced—a vengeful nemesis fueled by blood feud.",
        trailer_url="https://www.youtube.com/watch?v=aOb15GVFZxU",
        rating="PG-13",
        release_date="2023-05-19",
        movie_duration=141
    ),
    (
        title="Elemental",
        category="Animation/Adventure/Comedy",
        cast=["Leah Lewis", "Mamoudou Athie", "Ronnie del Carmen", "Shila Ommi"],
        director="Peter Sohn",
        producer="Denise Ream",
        synopsis="In a city where fire, water, land, and air residents live together, a fiery young woman and a go-with-the-flow guy discover something elemental: how much they actually have in common.",
        trailer_url="https://www.youtube.com/watch?v=hXzcyx9V0xw",
        rating="PG",
        release_date="2023-06-16",
        movie_duration=109
    ),
    (
        title="The Flash",
        category="Action/Adventure/Sci-Fi",
        cast=["Ezra Miller", "Michael Keaton", "Sasha Calle", "Ben Affleck"],
        director="Andy Muschietti",
        producer="Barbara Muschietti",
        synopsis="Barry Allen uses his super speed to change the past, but his attempt to save his family creates a world without heroes, forcing him to race for his life.",
        trailer_url="https://www.youtube.com/watch?v=hebWYacbdvc",
        rating="PG-13",
        release_date="2023-06-16",
        movie_duration=144
    ),
    (
        title="The Hunger Games: The Ballad of Songbirds and Snakes",
        category="Adventure/Drama/Sci-Fi",
        cast=["Tom Blyth", "Rachel Zegler", "Hunter Schafer", "Jason Schwartzman"],
        director="Francis Lawrence",
        producer="Nina Jacobson",
        synopsis="Years before he would become the tyrannical president of Panem, young Coriolanus Snow mentors a tribute in the 10th Hunger Games.",
        trailer_url="https://www.youtube.com/watch?v=RHiWxU9ZJIM",
        rating="PG-13",
        release_date="2023-11-17",
        movie_duration=157
    )
]
