# Generated by Django 5.0.9 on 2024-10-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('cast', models.TextField()),
                ('director', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('reviews', models.TextField()),
                ('trailer_url', models.URLField()),
                ('rating', models.CharField(max_length=10)),
                ('release_dates', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('showroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('screening_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_time', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('showrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.showroom')),
            ],
        ),
        migrations.AddField(
            model_name='showroom',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.theatre'),
        ),
    ]
