# Generated by Django 5.0.9 on 2024-10-29 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_dates',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
