# Generated by Django 5.0.9 on 2024-10-31 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie.showroom')),
            ],
            options={
                'unique_together': {('seat_number', 'showroom')},
            },
        ),
    ]
