# Generated by Django 5.0.9 on 2024-11-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_showroom_seat_count_seat_row'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
    ]
