# Generated by Django 5.0.9 on 2024-11-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_seat_unique_together_remove_seat_row'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_number', 'showroom')},
        ),
    ]
