# Generated by Django 5.0.9 on 2024-11-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_ticket_seat'),
        ('movie', '0010_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='seat_count',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
