# Generated by Django 5.0.9 on 2024-11-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=5),
        ),
    ]
